<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <style>
        body { font-family: 'Helvetica Neue', Arial, sans-serif; margin: 40px; color: #1f2937; line-height: 1.6; }
        .header { text-align: center; margin-bottom: 30px; padding-bottom: 20px; border-bottom: 2px solid #e5e7eb; }
        .header h1 { font-size: 24px; color: #4f46e5; margin: 0 0 5px 0; }
        .header p { color: #6b7280; margin: 0; font-size: 14px; }
        .score-section { text-align: center; margin: 30px 0; padding: 20px; background: #f9fafb; border-radius: 8px; }
        .score-circle { display: inline-block; width: 100px; height: 100px; border-radius: 50%; background: #e5e7eb; line-height: 100px; font-size: 36px; font-weight: bold; }
        .score-good { background: #dcfce7; color: #166534; }
        .score-ok { background: #fef9c3; color: #854d0e; }
        .score-bad { background: #fee2e2; color: #991b1b; }
        .section { margin-bottom: 25px; }
        .section h2 { font-size: 18px; color: #374151; border-bottom: 1px solid #e5e7eb; padding-bottom: 8px; margin-bottom: 15px; }
        .feedback-item { padding: 12px; margin-bottom: 10px; border-radius: 6px; border-left: 4px solid; }
        .feedback-critical { background: #fef2f2; border-color: #dc2626; }
        .feedback-warning { background: #fffbeb; border-color: #f59e0b; }
        .feedback-info { background: #eff6ff; border-color: #3b82f6; }
        .feedback-success { background: #f0fdf4; border-color: #22c55e; }
        .feedback-category { font-size: 12px; font-weight: 600; text-transform: uppercase; color: #6b7280; margin-bottom: 4px; }
        .feedback-message { font-size: 14px; margin-bottom: 4px; }
        .feedback-suggestion { font-size: 13px; color: #4b5563; font-style: italic; }
        .footer { text-align: center; margin-top: 40px; padding-top: 20px; border-top: 1px solid #e5e7eb; color: #9ca3af; font-size: 12px; }
        .meta { display: flex; justify-content: space-between; font-size: 13px; color: #6b7280; margin-bottom: 20px; }
    </style>
</head>
<body>
    <div class="header">
        <h1>ResumeAI Analysis Report</h1>
        <p>{{ $resume->title }}</p>
    </div>

    <div class="meta">
        <span>Resume: {{ $resume->original_filename }}</span>
        <span>Analysis Type: {{ ucfirst($analysis->type) }}</span>
        <span>Generated: {{ $generated_at }}</span>
    </div>

    <div class="score-section">
        @php
            $scoreClass = $score >= 80 ? 'score-good' : ($score >= 60 ? 'score-ok' : 'score-bad');
        @endphp
        <div class="score-circle {{ $scoreClass }}">{{ $score ?? '--' }}</div>
        <p style="margin-top: 10px; color: #6b7280;">ATS Compatibility Score</p>
    </div>

    @if($feedback->count() > 0)
    <div class="section">
        <h2>Detailed Feedback</h2>
        @foreach($feedback as $item)
        <div class="feedback-item feedback-{{ $item->severity }}">
            <div class="feedback-category">{{ $item->category }} @if($item->section) · {{ $item->section }} @endif</div>
            <div class="feedback-message">{{ $item->message }}</div>
            @if($item->suggestion)
            <div class="feedback-suggestion">Suggestion: {{ $item->suggestion }}</div>
            @endif
        </div>
        @endforeach
    </div>
    @endif

    @if($analysis->raw_response)
    <div class="section">
        <h2>Summary</h2>
        <p style="font-size: 14px;">
            @if(isset($analysis->raw_response['summary']))
                {{ $analysis->raw_response['summary'] }}
            @elseif(isset($analysis->raw_response['overall']))
                {{ $analysis->raw_response['overall'] }}
            @else
                Analysis completed successfully with {{ $feedback->count() }} feedback items.
            @endif
        </p>
    </div>
    @endif

    <div class="footer">
        <p>Generated by ResumeAI · {{ config('app.url') }}</p>
    </div>
</body>
</html>
